name = "ip-purity-checker"
main = "cloudflare/scheduled-worker.js"
compatibility_date = "2024-01-01"

# 环境变量
[vars]
ENVIRONMENT = "production"

# KV存储绑定 - 部署时会自动创建
# 如果您已有KV命名空间，请替换下面的ID
[[kv_namespaces]]
binding = "IP_CACHE"
id = "e0f261583d9c4eb59802ed2f4374a1e8"  # 从部署日志中获取的KV命名空间ID
preview_id = ""  # 预览环境ID

# 定时任务配置 - 北京时间00:00 (UTC 16:00)
[triggers]
crons = ["0 16 * * *"]  # 每日UTC 16:00执行 (北京时间00:00)
